apiVersion: v1
kind: Service
metadata:
  name: internal-app1
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8123
  - port: 9000
  selector:
    app: internal-app1
    
